runtime: go
api_version: go1

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
  secure: always
  redirect_http_response_code: 301
- url: /static
  static_dir: build/static
  secure: always
  redirect_http_response_code: 301
- url: /.*
  script: _go_app
  secure: always
  redirect_http_response_code: 301
